### ISSUE TITLE
Portuguese Translation Fixes

### ISSUE THREAD

**Issue by duartemelo** [glifem/extinction-translations#10]
press_enter_to_join = "Imprensa ~g~ENTER~w~ para começar a jogar.";
Fix it to: "Prime ~g~ENTER~w~ para começar a jogar."; 

Fix:
	pants = "Calças",
	neck = "Pescoço",

**Comment by PichotM** [comment]
Hello, sorry I missed this issue
@duartemelo what do you feel about the new translation?

**Comment by duartemelo** [comment]
Hello @PichotM ,
For me it is fine, but I really think that the portuguese community feel that there should be an option to change the language. I had to change my Windows language to English in order to get the server in English back again.

Thanks

**Comment by PichotM** [comment]
> Hello @PichotM ,
> For me it is fine, but I really think that the portuguese community feel that there should be an option to change the language. I had to change my Windows language to English in order to get the server in English back again.
> 
> Thanks

I will add this option ASAP
